#!/usr/bin/env bash
# Redirects to 301

sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i "25a\ \trewrite ^/redirect_me https://lingojam.com/EnglishtoEnglishLanguageTranslator permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
