#!/usr/bin/env bash
# nginx must be running as nginx user and nginx must be listening on all active IPs on port 8080
pkill apache2
sed -i "1s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s@80@8080@" /etc/nginx/sites-enabled/default
service nginx start
