#!/usr/bin/env bash
#Displays "To infinity and beyond indefinitely" every two secs
#and displays "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo I am invincible!!!' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
