#!/usr/bin/env bash
# Config nginx to listen to port 80
# sudo kill [pid] to kill nginx that was already running on port 8080
sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-available/default
sudo service nginx restart
