#!/usr/bin/env bash
#Gives information about the holbertonschool file

FILE="holbertonschool"
if [ -e $FILE ]
then
    echo "holbertonschool file exists"
    if [ -f $FILE ]
    then
	echo "holbertonschool is a regular file"
    else
	echo ""
    fi
    if [ -s $FILE ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
